name        : libxres
version     : 1.0.7
release     : 6
source      :
    - http://xorg.freedesktop.org/releases/individual/lib/libXres-1.0.7.tar.bz2 : 26899054aa87f81b17becc68e8645b240f140464cf90c42616ebb263ec5fa0e5
license     :
    - MIT
summary     : X11 Resource extension library
component   : xorg.library
builddeps   :
    - pkgconfig(resourceproto)
    - pkgconfig(xext)
    - pkgconfig32(xext)
    - pkgconfig(x11)
    - pkgconfig32(x11)
    - glibc-32bit-devel
    - libgcc-32bit
emul32      : yes
patterns    :
    - devel:
        - /usr/share/man
description : |
    libXRes provides an X Window System client interface to the Resource extension to the X protocol. The Resource extension allows for X clients to see and monitor the X resource usage of various clients (pixmaps, et al).
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
