name       : libxres
version    : 1.2.0
release    : 11
source     :
    - https://www.x.org/releases/individual/lib/libXres-1.2.0.tar.gz : 5b62feee09f276d74054787df030fceb41034de84174abec6d81c591145e043a
license    : MIT
component  : xorg.library
summary    : X11 Resource extension library
description: |
    libXRes provides an X Window System client interface to the Resource extension to the X protocol. The Resource extension allows for X clients to see and monitor the X resource usage of various clients (pixmaps, et al).
emul32     : yes
builddeps  :
    - pkgconfig32(xext)
    - pkgconfig32(x11)
    - pkgconfig(xproto)
patterns   :
    - devel :
        - /usr/share/man
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
